# Generated by Django 5.2.1 on 2025-05-22 10:26

import streaming.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_movie_added_at_season_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=streaming.models.movie_thumbnail_file_path),
        ),
    ]
