# Generated by Django 5.2.1 on 2025-05-23 08:25

import streaming.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_movie_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=streaming.models.episode_thumbnail_file_path),
        ),
    ]
