# Generated by Django 5.2.1 on 2025-05-23 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_episode_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='credits_time',
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
    ]
