# Generated by Django 5.2.1 on 2025-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_episode_credits_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='credits_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
